[bot]
TOKEN = "TOKEN"
TEST_TOKEN = "TEST_TOKEN"
API_URL = "https://api.telegram.org"
OWNER_ID = 123
USE_WEBHOOK = false

[database]
ENGINE_URL = "sqlite+aiosqlite:///dev-database.db"

[webhook]
WEB_SERVER_HOST = "127.0.0.1"
WEB_SERVER_PORT = 9332
BASE_URL = "http://127.0.0.1:9332"
MAIN_BOT_PATH = "/webhook/main"