name: Dependabot Auto Merge

on:
  pull_request:

jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GH_TOKEN }}
